name: 🚀 Déploiement automatique sur Serveur

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout du code
        uses: actions/checkout@v4

      - name: 🚀 Déploiement via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./
          security: loose
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**

      - name: 📥 Installer lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Mirror /webdata/dev/public vers _tmp_data_public (nouveaux fichiers uniquement)
        run: |
          mkdir -p _tmp_data_public
          lftp -e "
            set ssl:verify-certificate no;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
            mirror --only-newer /webdata/dev/public/ _tmp_data_public;
            bye
          "

      - name: 🧹 Supprimer index.php
        run: rm -f _tmp_data_public/index.php

      - name: 📤 Upload vers /public_html/dev/
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/dev/
          local-dir: ./_tmp_data_public/
          security: loose

